import Sidebar from "../../Components/Sidebar";
import MainTable from "../../Components/table";
import { IOrder } from "../../interfaces/IOrder";

const SalesPage: React.FC = () => {
  const headers = [
    { name: "Data", code: "date" },
    { name: "Produto", code: "product" },
    { name: "Quantidade", isNumeric: true, code: "quantity" },
    { name: "Valor de venda unitário", isNumeric: true, code: "unitPrice" },
    { name: "Valor de venda total", isNumeric: true, code: "totalPrice" },
    { name: "Cliente", code: "customer" },
    { name: "A pagar", code: "paid" },
  ];

  const data: IOrder[] = [
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
    {
      date: "24-04-2024",
      product: "T-Shirt",
      quantity: 5,
      unitPrice: 20.0,
      totalPrice: 100.0,
      customer: "Creuza",
      paid: true,
    },
  ];
  return (
    <>
      <Sidebar selected="sales" />;
      <MainTable headers={headers} data={data} />
    </>
  );
};

export default SalesPage;
